[로또] 김유권 미션 제출합니다.
woowacourse-precourse/javascript-lotto pull request #553
Opened 2022-11-15 14:55 UTC by ukkodeveloper

인증 만료로 인해서 급하게 복사 붙여넣어서 제출합니다. 

c607098 (HEAD -> ukkodeveloper) docs: README.md TIL 추가
59cce0b (errorHandle) docs: README.md 기능 구현 목록 수정
c879eb1 test: 당첨 경우 테스트 추가
234d025 test: lotto class 테스트 추가
683a4f5 style: 컨벤션에 맞게 추가 개행
c981aa2 style: 정규표현식 주석 추가 및 전반적인 코드 개행 여부 확인
bd475f8 refactor: Lotto 클래스 getSameNumberCount 메소드로 분리
0797f11 refactor: 부수효과를 줄이기 위해 배열 스프레드 연산자 사용
f5c8bfa refactor: 변수명 변경
eb57ea8 refactor: checkNumberListInRange를 forEach 대신 every로 변경
6848516 refactor: 상수 및 메세지 객체 Object.freeze() 해주어 다른 모듈에서 변경할 수 없도록 수정
d9849fc fix: 변수 변경에 따른 미적용 변수 수정하여 버그 해결
a1bbdf4 refactor: lotto grade -> lotto match  적절한 변수명으로 변경
e2f868f refactor: lotto 숫자 출력시 배열이 아닌 문자열로 출력
44475db feat: 로또 잘못 입력시 에러 발생
bbe4662 feat: 복권 입력시 예외처리 추가
906f0bc feat: 구매 금액 입력시 예외사항 추가
f4cf263 feat: 당첨 결과 출력
18dafce fix: 로또 구매자는 6개의 번호만 받을 수 있음. 보너스 번호를 주었는데 이부분 수정
3d58364 feat: 당첨 로또에 대한 등수 리스트 계산
08ae700 feat: 당첨 순위에 맞는 금액 기준표 작성
94bed0d feat: (로또 발행) 구매에 대한 안내 메세지 출력
dd9b038 feat: (로또 발행) 구매 금액 입력 시 로또 번호 생성
6111e1e docs: README.md 기능 구현 목록 작성
0cd08cc (origin/main, origin/HEAD, main) feat: setup precourse lotto project

2022-11-16 01:21 UTC, confidential-nt reviewed
제가 오히려 더 한 수 배워갑니다..리뷰라기엔 전혀 도움이 안되는 것 같아 남기기가 망설여지지만 그래도 남겨봅니다!

2022-11-16 01:21 UTC, confidential-nt commented on src/LottoGame.js
> +    this.buyer = new Buyer();
이렇게 철저하게 클래스를 분리하여 작성하신 점 본받고 싶습니다!

2022-11-16 01:21 UTC, confidential-nt commented on src/utils/helper.js
> +const deepFreeze = (obj) => {
이런 고급 기술(?) 사용하시는 것도 너무 좋은 것 같습니다

2022-11-16 01:21 UTC, confidential-nt commented on src/Validator.js
> +      throw new Error(ERROR_MESSAGE.priceOnlyThousands);
하드 코딩을 철저하게 배제하신 점 인상깊고 본받고 싶습니다!

2022-11-16 02:27 UTC, turtle601 commented on src/utils/winningPrice.js
> +module.exports = WINNING_PRICE;
코드를 전체적으로 너무 잘짜서 무슨 코멘트를 드려야할지 모르겠습니다 ㅎㅎ

유권님 코드 보면서 많이 배우게 되네요 ㅎㅎ 감사힙나다 👍👍👍

2022-11-16 04:37 UTC, letsjo commented
1주차 부터 유권님 한테 많이 배우고 있습니다 😀 전체적으로 코드 잘 봤읍니다 👀👀
코멘트 달 게 마땅히 없는 것 같아서 바로 전체코멘트로 왔습니다!  

날짜 별로 📑 Docs 정리 하신 것 부터 회고까지 적어놓으신 것도 잘 보고 갑니다👍

클래스는 어떻게 나눠야 하는지🤔..
네이밍은 어떻게 짓는게 좋을지🤔.. 

등 저의 부족한 부분들을 많이 배우고 갑니다!

유권님의 리뷰 한 번 받아보고 싶습니다! 한 번 답방 부탁드리겠습니다!

2022-11-16 06:25 UTC, ukkodeveloper commented on src/utils/helper.js
> +const deepFreeze = (obj) => {
저도 이번에 알게 되어서 적용해봤어요!

2022-11-16 10:28 UTC, evencoding reviewed
`객체를 객체처럼`에 대해 많이 고민하신게 느껴져요!!
구조를 따라 그려보는 것만으로도 큰 도움이 됐습니다 감사합니다!

2022-11-16 10:28 UTC, evencoding commented on src/LottoGame.js
> +    const ticketCount = money / 1000;
1000은 로또 하나의 가격을 의미하니 따로 변수화 시켜주었다면 좋았을 것 같아요!

2022-11-16 10:28 UTC, evencoding commented on src/LottoGame.js
> +    this.organizer.setBonusNumber(Number(bonusNumber));
당첨 번호에서는 공백에 대한 처리를 해주셨는데 보너스 넘버에서는 따로 처리하지 않으신 이유가 있을까요??

2022-11-21 07:30 UTC, ukkodeveloper commented on src/utils/winningPrice.js
> +module.exports = WINNING_PRICE;
저는 오히려 준승님 코드보면서 배우는 걸요 🥲

2022-11-21 07:31 UTC, ukkodeveloper commented on src/LottoGame.js
> +    const ticketCount = money / 1000;
놓친 부분 캐치해주셔서 감사합니다!

2022-11-21 07:32 UTC, ukkodeveloper commented on src/players/Organizer.js
> +  }
넵 ! 맞습니다. 제가 필드 개념이 부족해서 적용 못했습니다🥲 알려주셔서 감사해요

2023-07-05 05:12 UTC, cruelladevil requested changes
R 테스트 제목입니다.

2023-07-05 05:12 UTC, cruelladevil commented on src/LottoSystem.js
> +  }
1 - R 테스트 입니다.

2023-07-05 05:12 UTC, cruelladevil commented on src/LottoSystem.js
> +  }
2 - R 테스트입니다.

2023-08-31 05:26 UTC, closed without merging